educationCMS/educa/article/urls.py
from django.urls import path
from . import views 
from .feeds import LatestPostsFeed

app_name = 'article'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    # path('test/', views.test, name='articletest'),
    # path('article_list/', views.article_list, name='article_list'),
    path('article_detail/', views.article_detail, name='article_detail'),
]

educationCMS/educa/educa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import user.urls
import article.urls
import home.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(user.urls,namespace='account')),
    path('article/', include(article.urls,namespace='article')),
    path('', include(home.urls,namespace='home')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

educationCMS/educa/home/urls.py
from django.urls import path, include
from django.urls import reverse_lazy
from . import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='home'),
]

educationCMS/educa/article/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model): 
    STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    ) 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250,  
                            unique_for_date='publish') 
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='blog_posts') 
    body = models.TextField() 
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title

    def get_absolute_url(self):
        return reverse('article:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ('created',) 
 
    def __str__(self): 
        return 'Comment by {} on {}'.format(self.name, self.post)

educationCMS/educa/article/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	name = forms.CharField(label="name", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'name'}))
	email = forms.CharField(label="email", widget=forms.EmailInput(attrs={'class': 'form-control','placeholder':'email'}))
	body = forms.CharField(label="body", widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'body'}))

	class Meta:
	    model = Comment
	    fields = ('name', 'email', 'body')

educationCMS/educa/article/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.db.models import Count
from taggit.models import Tag
from .forms import CommentForm

def article_detail(request):
  return render(request,'arttest/article_detail.html')

# def test(request, tag_slug=None):
#     object_list = Post.published.all()
#     latest_posts = Post.published.order_by('-publish')[:4]
#     tag = None

#     if tag_slug:
#         tag = get_object_or_404(Tag, slug=tag_slug)
#         object_list = object_list.filter(tags__in=[tag])

#     paginator = Paginator(object_list, 3) # 3 posts in each page
#     page = request.GET.get('page')
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)

#     return render(request,
#                   'arttest/arttest.html',
#                   {'page': page,
#                    'posts': posts,
#                    'tag': tag,
#                    'latest_posts': latest_posts})

# def article_list(request):
#   article_list = Post.published.all()
#   paginator = Paginator(article_list, 2)
#   page = request.GET.get('page')
#   try:
#     articles = paginator.page(page)
#   except PageNotAnInteger:
#     articles = paginator.page(1)
#   except EmptyPage:
#     articles = paginator.page(paginator.num_pages)
#   return render(request,'arttest/aritcle_list.html',{'article_list': articles})


# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    latest_posts = Post.published.order_by('-publish')[:4]
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'article/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,
                   'latest_posts': latest_posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'article/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

educationCMS/educa/article/templates/article/post/detail.html
{% extends "edu_base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}Articles{% endblock %}

{% block content %}
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area bg-img" style="background-image: url({% static "img/bg-img/breadcumb.jpg" %});">
    </div>
    <!-- ##### Breadcumb Area End ##### -->

        <section class="section gb nopadtop">
            <div class="container">
                <div class="boxed">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="content blog-list">
                                <div class="blog-wrapper clearfix">
                                    <div class="blog-meta">
                                        <small>Tags:
                                          {% for tag in post.tags.all %}
                                            <a href="{% url "article:post_list_by_tag" tag.slug %}">
                                              {{ tag.name }}
                                            </a>
                                            {% if not forloop.last %}, {% endif %}
                                          {% endfor %}
                                        </small>   
                                        <h3>{{ post.title }}</h3>
                                        <ul class="mylistInline">
                                            <li>{{ post.publish }}</li>
                                            <li><span>written by</span> <a href="#">{{ post.author }}</a></li>
                                        </ul>
                                    </div><!-- end blog-meta -->

                                    <div class="blog-media">
                                        <img src="{% static "temp_upload/blog_01.jpg" %}" alt="" class="img-responsive img-rounded">
                                    </div><!-- end media -->

                                    <div class="blog-desc-big">
                                        <p class="lead">lead Space ~~~~~~~</p>

                                        <p> {{ post.body|markdown }} </p>


                                        <hr class="invis">

                                        <div class="tags-widget">   
                                            <ul class="mylistInline">
                                                {% for tag in post.tags.all %}
                                                    <li><a href="{% url "article:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></li>
                                                    {% if not forloop.last %}, {% endif %} 
                                                {% endfor%}  
                                            </ul>
                                        </div><!-- end list-widget -->

                                    </div><!-- end desc -->
                                </div><!-- end blog -->
                            </div><!-- end content -->

                            <div class="authorbox">
                                <div class="site-publisher clearfix">
                                    <img src="{% static "temp_upload/people_10.jpeg" %}" alt="" class="img-responsive img-circle">
                                    <a href="single-agency.html" title=""><h4><small>about</small> <span>Martin Martines</span></h4></a>
                                    <p>Exercitation photo booth stumptown tote bag Banksy, elit small batch freegan sed. Craft beer elit seitan exercitation, photo booth.</p>

                                    <div class="authorbox-social">
                                        <ul class="mylistInline">
                                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                                            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                            <li><a href="#"><i class="fa fa-envelope-o"></i></a></li>
                                        </ul><!-- end list -->
                                    </div><!-- end share -->
                                </div><!-- end publisher -->
                            </div><!-- end details -->

                            <div class="content boxed-comment clearfix">
                                {% with comments.count as total_comments %}
                                    <h3 class="small-title">
                                     {{ total_comments }} comment{{ total_comments|pluralize }}
                                    </h3>
                                {% endwith %}
                                <div class="comments-list">
                                    {% for comment in comments %}
                                        <div class="media">
                                            <a class="media-left" href="#">
                                                <img src="{% static "temp_upload/people_12.jpeg" %}" alt="" class="img-circle">
                                            </a>
                                            <div class="media-body">
                                                <h4 class="media-heading user_name">Comment {{ forloop.counter }} by {{ comment.name }}</h4>
                                                <p>{{ comment.body|linebreaks }}</p>
                                                <p class="pull-right"><small>{{ comment.created }}</small></p>
                                            </div>
                                        </div>
                                    {% empty %}
                                        <p>There are no comments yet.</p>
                                    {% endfor %}
                                </div>
                            </div><!-- end content -->

                            <div class="content boxed-comment clearfix">
                                <h3 class="small-title">Leave a Comment</h3>
                                <form action="." method="post">
                                    {% csrf_token %}
                                    {% for field in comment_form %}
                                        {{ field }}
                                        {{ field.errors }}
                                        {% if field.help_text %}
                                            <p class="help text-small text-muted">{{ field.help_text|safe}}</p>
                                        {% endif %}
                                    {% endfor %}
                                  <button class="btn academy-btn mt-30" type="submit">Leave a Comment</button>
                                </form>
                            </div><!-- end content -->

                        </div><!-- end col -->

                        <div class="sidebar col-md-4">
                            <div class="widget clearfix">
                                <div class="banner-widget">
                                    <img src="{% static "temp_upload/banner.jpeg" %}" alt="" class="img-responsive img-rounded">
                                </div>
                            </div>

                            <div class="widget clearfix">
                                <h3 class="widget-title">Popular Posts</h3>
                                <div class="post-widget">
                                    <div class="media">
                                        <img src="{% static "temp_upload/blog_small_01.jpg" %}" alt="" class="img-responsive alignleft img-rounded">
                                        <div class="media-body">
                                            <h5 class="mt-0"><a href="blog-single.html">Learning English Like a Pro..</a></h5>
                                            <div class="blog-meta">
                                                <ul class="mylistInline">
                                                    <li>4 days ago</li>
                                                    <li><span>by</span> <a href="#">Edulogy Team</a></li>
                                                </ul>
                                            </div><!-- end blog-meta -->
                                        </div>
                                    </div>

                                    <div class="media">
                                        <img src="{% static "temp_upload/blog_small_02.jpg" %}" alt="" class="img-responsive alignleft img-rounded">
                                        <div class="media-body">
                                            <h5 class="mt-0"><a href="blog-single.html">How to create a beautiful website with Bootstrap</a></h5>
                                            <div class="blog-meta">
                                                <ul class="mylistInline">
                                                    <li>5 days ago</li>
                                                    <li><span>by</span> <a href="#">Boby DOE</a></li>
                                                </ul>
                                            </div><!-- end blog-meta -->
                                        </div>
                                    </div>

                                    <div class="media">
                                        <img src="{% static "temp_upload/blog_small_03.jpg" %}" alt="" class="img-responsive alignleft img-rounded">
                                        <div class="media-body">
                                            <h5 class="mt-0"><a href="blog-single.html">Don't forget to update your Google web master tools</a></h5>
                                            <div class="blog-meta">
                                                <ul class="mylistInline">
                                                    <li>6 days ago</li>
                                                    <li><span>by</span> <a href="#">Martin</a></li>
                                                </ul>
                                            </div><!-- end blog-meta -->
                                        </div>
                                    </div>
                                </div><!-- end post-widget -->
                            </div><!-- end widget -->

                            <div class="widget clearfix">
                                <h3 class="widget-title">Subscribe Our Newsletter</h3>
                                <div class="newsletter-widget">
                                    <p>You can opt out of our newsletters at any time. See our <a href="#">privacy policy</a>.</p>
                                    <form class="form-inline" role="search">
                                        <div class="form-1">
                                            <input type="text" class="form-control" placeholder="Enter email here..">
                                            <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane-o"></i></button>
                                        </div>
                                    </form>
                                </div><!-- end newsletter -->
                            </div><!-- end widget -->

                            <div class="widget clearfix">
                                <h3 class="widget-title">Popular Tags</h3>
                                <div class="tags-widget">   
                                    <ul class="mylistInline">
                                        <li><a href="#">course</a></li>
                                        <li><a href="#">web design</a></li>
                                        <li><a href="#">development</a></li>
                                        <li><a href="#">language</a></li>
                                        <li><a href="#">teacher</a></li>
                                        <li><a href="#">speaking</a></li>
                                        <li><a href="#">material</a></li>
                                        <li><a href="#">css3</a></li>
                                        <li><a href="#">html</a></li>
                                        <li><a href="#">learning</a></li>
                                    </ul>
                                </div><!-- end list-widget -->
                            </div><!-- end widget -->
                        </div><!-- end sidebar -->
                    </div><!-- end row -->
                </div><!-- end boxed -->
            </div><!-- end container -->
        </section>

{% endblock %}

educationCMS/educa/article/templates/article/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

educationCMS/educa/article/templates/article/post/list.html
{% extends "edu_base.html" %}
{% load article_tags %}
{% load staticfiles %}

{% block title %}Articles{% endblock %}

{% block content %}
    <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb-area bg-img" style="background-image: url({% static "img/bg-img/breadcumb.jpg" %});">
        <div class="bradcumbContent">
            <h2>Articles</h2>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->


    <section class="section gb nopadtop">
        <div class="container">
            <div class="boxed">
                <div class="row">
                    <div class="col-md-8">
                        {% for post in posts %}
                            <div class="content blog-list">
                                <div class="blog-wrapper clearfix">
                                    <div class="blog-meta">
                                        <small>Tags:
                                          {% for tag in post.tags.all %}
                                            <a href="{% url "article:post_list_by_tag" tag.slug %}">
                                              {{ tag.name }}
                                            </a>
                                            {% if not forloop.last %}, {% endif %}
                                          {% endfor %}
                                        </small>                                      
                                        <h3><a href="{{ post.get_absolute_url }}" title="">{{ post.title }}</a></h3>
                                        <ul class="mylistInline">
                                            <li>{{ post.publish }}</li>
                                            <li><span>written by</span> <a href="#">{{ post.author }}</a></li>
                                        </ul>
                                    </div><!-- end blog-meta -->

                                    <div class="blog-media">
                                        <a href="blog-single.html" title=""><img src="{% static "temp_upload/blog_01.jpg" %}" alt="" class="img-responsive img-rounded"></a>
                                    </div><!-- end media -->

                                    <div class="blog-desc-big">
                                        <p class="lead">lead place ~~~~~~~~~~</p>
                                        <p>{{ post.body|markdown|truncatewords_html:30 }}</p>
                                        <a href="blog-single.html" class="btn btn-primary">Read More</a>
                                    </div><!-- end desc -->
                                </div><!-- end blog -->
                            </div><!-- end content -->
                        {% endfor %}

                        <div class="row">
                            <div class="col-md-12">
                                {% include "paginationnew.html" with page=posts %}                                       
                            </div><!-- end col -->
                        </div><!-- end row -->
                    </div><!-- end col -->

                    <div class="sidebar col-md-4">
                        <div class="widget clearfix">
                            <div class="banner-widget">
                                <img src="{% static "temp_upload/banner.jpeg" %}" alt="" class="img-responsive img-rounded">
                            </div>
                        </div>

                        <div class="widget clearfix">
                            <h3 class="widget-title">Popular Posts</h3>
                            <div class="post-widget">
                                {% for post in latest_posts %}
                                <div class="media">
                                    <img src="{% static "temp_upload/blog_small_01.jpg" %}" alt="" class="img-responsive alignleft img-rounded">
                                    <div class="media-body">
                                        <h5 class="mt-0"><a href="">{{ post.title }}</a></h5>
                                        <div class="blog-meta">
                                            <ul class="mylistInline">
                                                <li>{{ post.publish }}</li>
                                                <li><span>by</span> <a href="#">{{ post.author }}</a></li>
                                            </ul>
                                        </div><!-- end blog-meta -->
                                    </div>
                                </div>
                                {% endfor %}
                            </div><!-- end post-widget -->
                        </div><!-- end widget -->

                        <div class="widget clearfix">
                            <h3 class="widget-title">Subscribe to my RSS feed</h3>
                            <div class="newsletter-widget">
                                <p>You can opt out of our newsletters at any time. Go <a href="{% url "article:post_feed" %}">Subscribe</a>.</p>
                                <form class="form-inline" role="search">
                                    <div class="form-1">
                                        <input type="text" class="form-control" placeholder="Enter email here..">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane-o"></i></button>
                                    </div>
                                </form>
                            </div><!-- end newsletter -->
                        </div><!-- end widget -->

                        <div class="widget clearfix">
                            <h3 class="widget-title">Popular Tags</h3>
                            <div class="tags-widget">   
                                <ul class="mylistInline">
                                    <li><a href="#">course</a></li>
                                    <li><a href="#">web design</a></li>
                                    <li><a href="#">development</a></li>
                                    <li><a href="#">language</a></li>
                                    <li><a href="#">teacher</a></li>
                                    <li><a href="#">speaking</a></li>
                                    <li><a href="#">material</a></li>
                                    <li><a href="#">css3</a></li>
                                    <li><a href="#">html</a></li>
                                    <li><a href="#">learning</a></li>
                                </ul>
                            </div><!-- end list-widget -->
                        </div><!-- end widget -->
                    </div><!-- end sidebar -->
                </div><!-- end row -->
            </div><!-- end boxed -->
        </div><!-- end container -->
    </section>

{% endblock %}